# This file was generated by GoReleaser. DO NOT EDIT.
cask "recco" do
  name "recco"
  desc "A terminal app that recommends Steam games using Gemini AI"
  homepage "https://github.com/vitalii-komenda/Recco"
  version "0.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "recco"

  on_macos do
    on_intel do
      url "https://github.com/vitalii-komenda/Recco/releases/download/v#{version}/recco_#{version}_darwin_amd64.tar.gz"
      sha256 "c7cd8a9ad62d8e8399437eced060a3d005c7885089d42c2f3999c4f3e40ffaed"
    end
    on_arm do
      url "https://github.com/vitalii-komenda/Recco/releases/download/v#{version}/recco_#{version}_darwin_arm64.tar.gz"
      sha256 "7522e0938c642e811b1d06d3394d4381a79ff0f76582aea058a1b794ba1b2e13"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/vitalii-komenda/Recco/releases/download/v#{version}/recco_#{version}_linux_amd64.tar.gz"
      sha256 "657a0da1dc1112467552cd121a6ba2708d3f002a50158a5207a86de38b38007a"
    end
    on_arm do
      url "https://github.com/vitalii-komenda/Recco/releases/download/v#{version}/recco_#{version}_linux_arm64.tar.gz"
      sha256 "4faf003d332b118faefe92ae94a4ad8f9020f6cdb4e9286aa8925fe51113a0bd"
    end
  end

  # No zap stanza required
end
