# This file was generated by GoReleaser. DO NOT EDIT.
cask "recco" do
  name "recco"
  desc "A terminal app that recommends Steam games using Gemini AI"
  homepage "https://github.com/vitalii-komenda/Recco"
  version "0.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "recco"

  on_macos do
    on_intel do
      url "https://github.com/vitalii-komenda/Recco/releases/download/v#{version}/recco_#{version}_darwin_amd64.tar.gz"
      sha256 "b52b8f9b1a986bd9f6eed29ddd73496122aaec39c374cc446165adec82572f32"
    end
    on_arm do
      url "https://github.com/vitalii-komenda/Recco/releases/download/v#{version}/recco_#{version}_darwin_arm64.tar.gz"
      sha256 "820d59160b7842ac11a3bbbaef356a7d53778c5266626a8e758a6c4ba66b15e2"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/vitalii-komenda/Recco/releases/download/v#{version}/recco_#{version}_linux_amd64.tar.gz"
      sha256 "d204d9d9a2c4d4faccddfc12cf1413ecbe85da48f5b5d8d2607b8f666efda7b4"
    end
    on_arm do
      url "https://github.com/vitalii-komenda/Recco/releases/download/v#{version}/recco_#{version}_linux_arm64.tar.gz"
      sha256 "21836e957560c8ccd74818f5097057bb8803dd44c7094562af30e91548f36086"
    end
  end

  # No zap stanza required
end
