# This file was generated by GoReleaser. DO NOT EDIT.
cask "recco" do
  name "recco"
  desc "A terminal app that recommends Steam games using Gemini AI"
  homepage "https://github.com/vitalii-komenda/Recco"
  version "0.0.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "recco"

  on_macos do
    on_intel do
      url "https://github.com/vitalii-komenda/Recco/releases/download/v#{version}/recco_#{version}_darwin_amd64.tar.gz"
      sha256 "3b226420104aa8bd149d9019bd02de4de1976308af7759fc9d048501fb4104d4"
    end
    on_arm do
      url "https://github.com/vitalii-komenda/Recco/releases/download/v#{version}/recco_#{version}_darwin_arm64.tar.gz"
      sha256 "9eb916baea46c2ceea7c16582f1869ec1ce57c51e3dddc51c13b8ae5308f840d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/vitalii-komenda/Recco/releases/download/v#{version}/recco_#{version}_linux_amd64.tar.gz"
      sha256 "ed97abcd0dc8a4deecba98d924e03422ce16fae9a4fc4278578fee7599c1befa"
    end
    on_arm do
      url "https://github.com/vitalii-komenda/Recco/releases/download/v#{version}/recco_#{version}_linux_arm64.tar.gz"
      sha256 "d39373fe9b52aa5d304c134340e24becb45304ea08950ac4042b6a6aed11ff05"
    end
  end

  # No zap stanza required
end
